# Generated by Django 4.1.7 on 2023-03-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(verbose_name='Release date')),
                ('on_netfilx', models.BooleanField(default=False)),
                ('profit', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
