# Generated by Django 4.1.7 on 2023-03-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_screenings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenings',
            new_name='Screening',
        ),
    ]
