# Generated by Django 4.1.7 on 2023-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_screenings_screening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name='Birth date')),
                ('married', models.BooleanField(default=False)),
                ('films', models.IntegerField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
