# Generated by Django 4.1.7 on 2023-03-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='films.film'),
        ),
    ]
