# Generated by Django 4.1.7 on 2023-03-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_screening_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActedInFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='films.actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='films.film')),
            ],
        ),
    ]
