# Generated by Django 4.1.7 on 2023-05-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_film_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
