# Generated by Django 4.1.7 on 2023-05-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_film_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmonlocation',
            name='nr_of_scenes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
